services:
  - type: web
    name: todo-app-api-production
    plan: starter
    runtime: python
    region: oregon
    buildCommand: |
      cd backend &&
      chmod +x start.sh &&
      pip install --upgrade pip setuptools wheel &&
      pip install -r requirements.txt --no-cache-dir
    startCommand: |
      cd backend &&
      chmod +x start.sh &&
      ./start.sh
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        value: postgresql://todo_user:[PASSWORD]@dpg-d1ks3615pdvs73b82g7g-a.oregon-postgres.render.com:5432/todo_db_22qu
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: APP_NAME
        value: "TODO App API"
      - key: APP_VERSION
        value: "4.0.0"
      - key: CORS_ORIGINS
        value: '["https://your-frontend-url.onrender.com", "http://localhost:3000"]'
      - key: MAX_REQUEST_SIZE
        value: "1048576"
      - key: RATE_LIMIT_AUTH
        value: "5/minute"
      - key: RATE_LIMIT_API
        value: "50/minute"
      - key: JWT_ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_HOURS
        value: "12"
      - key: HOST
        value: "0.0.0.0"
    healthCheckPath: /health